---
abstract: 'IRCv3.2 parser without regular expressions'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Scalar::Util: 0
  Test::Deep: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Filter-IRCv3
recommends:
  POE::Filter: 1
requires:
  Carp: 0
  perl: v5.8.0
resources:
  repository: git://github.com/avenj/poe-filter-ircv3.git
version: 0.046000
