---
abstract: 'POE::Filter::IRCD with IRCv3.2 message tags'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Filter-IRCv3
requires:
  Carp: 0
  POE::Filter: 0
  parent: 0
  perl: v5.8.9
  strictures: 1
resources:
  repository: git://github.com/avenj/poe-filter-ircv3.git
version: 0.040001
