---
abstract: 'Fast IRCv3.2 parser for POE or stand-alone use'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  List::Util: 0
  Scalar::Util: 0
  Test::Deep: 0
  Test::More: 0.88
  version: 0.77
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Filter-IRCv3
recommends:
  POE::Filter: 1
requires:
  Carp: 0
  perl: v5.8.0
resources:
  repository: git://github.com/avenj/poe-filter-ircv3.git
version: 1.001001
